package com.amnesica.kryptey.inputmethod.signalprotocol.storage;

import java.security.GeneralSecurityException;
import java.util.Arrays;

import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;

/**
 * AES-256-GCM envelope encryption.
 *
 * <p>Envelope layout:
 *
 * <pre>
 *   byte 0        format version (currently {@link #VERSION})
 *   bytes 1..12   96-bit GCM nonce
 *   bytes 13..    ciphertext with a trailing 128-bit authentication tag
 * </pre>
 *
 * <p>The nonce is generated by the JCE provider rather than by this class. That is not a stylistic
 * choice: an Android Keystore key is created with {@code randomizedEncryptionRequired = true}, which
 * makes it reject a caller-supplied IV with {@code CALLER_NONCE_PROHIBITED}. Passing our own nonce
 * would therefore fail on every real device while working perfectly against a desktop JCE key.
 *
 * <p>A 96-bit provider-random nonce is sound here. With q seals under one key the collision
 * probability is about q^2/2^97; NIST SP 800-38D caps random-IV use at 2^32 invocations, and this
 * caller performs roughly eight seals per message, so the bound is never approached in practice.
 *
 * <p>Subclasses supply the key. Everything in this class is plain JCE and therefore runs — and is
 * tested — on a desktop JVM.
 */
public abstract class GcmCryptoBox implements CryptoBox {

  static final byte VERSION = 0x01;
  static final int NONCE_BYTES = 12;
  static final int TAG_BITS = 128;
  private static final int TAG_BYTES = TAG_BITS / 8;
  private static final int HEADER_BYTES = 1 + NONCE_BYTES;

  /**
   * The AES-256 key to use. Called per operation rather than cached in this class so that a
   * Keystore-backed subclass can invalidate and re-resolve its handle.
   */
  protected abstract SecretKey key() throws StorageCryptoException;

  @Override
  public byte[] seal(final byte[] plaintext, final byte[] aad) throws StorageCryptoException {
    if (plaintext == null) throw new StorageCryptoException("plaintext is null");
    if (aad == null) throw new StorageCryptoException("aad is null");

    try {
      final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
      // No GCMParameterSpec: let the provider pick the nonce. Supplying one is rejected outright by
      // an Android Keystore key (see the class javadoc).
      cipher.init(Cipher.ENCRYPT_MODE, key());
      cipher.updateAAD(aad);

      final byte[] nonce = cipher.getIV();
      if (nonce == null || nonce.length != NONCE_BYTES) {
        // The envelope format has a fixed-width nonce field, so a provider that chose a different
        // length would silently produce blobs this class could never open again.
        throw new StorageCryptoException("provider chose an unexpected GCM nonce length: "
            + (nonce == null ? "null" : nonce.length));
      }

      final byte[] ciphertext = cipher.doFinal(plaintext);

      final byte[] envelope = new byte[HEADER_BYTES + ciphertext.length];
      envelope[0] = VERSION;
      System.arraycopy(nonce, 0, envelope, 1, NONCE_BYTES);
      System.arraycopy(ciphertext, 0, envelope, HEADER_BYTES, ciphertext.length);
      return envelope;
    } catch (GeneralSecurityException | RuntimeException e) {
      throw new StorageCryptoException("could not seal storage blob", e);
    }
  }

  @Override
  public byte[] open(final byte[] envelope, final byte[] aad) throws StorageCryptoException {
    if (envelope == null) throw new StorageCryptoException("envelope is null");
    if (aad == null) throw new StorageCryptoException("aad is null");
    // A valid envelope is header + at least the GCM tag. Anything shorter is truncated, and
    // rejecting it here keeps Cipher from being handed a nonsensical length.
    if (envelope.length < HEADER_BYTES + TAG_BYTES) {
      throw new StorageCryptoException("envelope too short: " + envelope.length + " bytes");
    }
    if (envelope[0] != VERSION) {
      throw new StorageCryptoException("unsupported storage envelope version: " + envelope[0]);
    }

    final byte[] nonce = Arrays.copyOfRange(envelope, 1, HEADER_BYTES);
    try {
      final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
      cipher.init(Cipher.DECRYPT_MODE, key(), new GCMParameterSpec(TAG_BITS, nonce));
      cipher.updateAAD(aad);
      return cipher.doFinal(envelope, HEADER_BYTES, envelope.length - HEADER_BYTES);
    } catch (GeneralSecurityException | RuntimeException e) {
      // GeneralSecurityException covers AEADBadTagException. RuntimeException is also required:
      // JCE providers throw unchecked ProviderException and IllegalArgumentException for some
      // malformed inputs, and those would otherwise bypass StorageCryptoException entirely and
      // propagate out of LatinIME.setInputView() - the crash-on-every-raise mode this whole
      // exception type exists to eliminate.
      //
      // Deliberately not distinguishing the causes in the message: the caller must treat every one
      // of them as "this blob is not trustworthy".
      throw new StorageCryptoException("could not open storage blob", e);
    }
  }
}
