package com.amnesica.kryptey.inputmethod.signalprotocol;

import com.amnesica.kryptey.inputmethod.signalprotocol.chat.Contact;
import com.amnesica.kryptey.inputmethod.signalprotocol.chat.StorageMessage;
import com.amnesica.kryptey.inputmethod.signalprotocol.util.JsonUtil;

import org.junit.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.Instant;
import java.util.ArrayList;

/**
 * Not a test of behaviour: this regenerates the on-disk JSON fixtures used by
 * {@link JacksonCompatTest}.
 *
 * <p>The fixtures must be produced by the Jackson version we are migrating <em>from</em>, so this
 * is run deliberately, with that older version pinned in app/build.gradle, and the result is
 * committed. It is skipped in normal runs because a fixture regenerated by the current Jackson
 * would make {@link JacksonCompatTest} tautological — it would only ever prove that Jackson can
 * read its own output, which is exactly the assumption under test.
 *
 * <p>To regenerate:
 * <pre>
 *   1. pin the old Jackson version in app/build.gradle
 *   2. ./gradlew testDebugUnitTest --tests '*FixtureGenerator*' -Dkryptey.writeFixtures=true
 *   3. restore the new Jackson version
 * </pre>
 */
public class FixtureGenerator {

  private static final String FIXTURE_DIR = "src/test/resources/fixtures";

  @Test
  public void writeProtocolStoreFixture() throws IOException {
    // Reports as skipped rather than passed. Returning silently would count this assertion-free
    // method among the suite's passing tests on every CI run, inflating the total with a test that
    // can never fail.
    org.junit.Assume.assumeTrue("set -Dkryptey.writeFixtures=true to regenerate fixtures",
        Boolean.getBoolean("kryptey.writeFixtures"));

    SignalProtocolMain.testIsRunning = true;
    SignalProtocolMain.initialize(null);
    final Account account = SignalProtocolMain.getInstance().getAccount();

    // A contact and a message so the fixture also covers the java.time.Instant path through
    // jackson-datatype-jsr310, which is the part of the upgrade most likely to drift.
    final ArrayList<Contact> contacts = new ArrayList<>();
    contacts.add(new Contact("Ada", "Lovelace", account.getSignalProtocolAddress().getName(),
        account.getDeviceId(), true));
    account.setContactList(contacts);

    final ArrayList<StorageMessage> messages = new ArrayList<>();
    messages.add(new StorageMessage(
        account.getSignalProtocolAddress().getName(),
        account.getSignalProtocolAddress().getName(),
        account.getSignalProtocolAddress().getName(),
        Instant.ofEpochMilli(1_685_361_429_000L),
        "fixture message"));
    account.setUnencryptedMessages(messages);

    final File dir = new File(FIXTURE_DIR);
    if (!dir.isDirectory() && !dir.mkdirs()) {
      throw new IOException("could not create " + dir.getAbsolutePath());
    }

    write(dir, "protocol-store.json", JsonUtil.toJson(account.getSignalProtocolStore()));
    write(dir, "metadata-store.json", JsonUtil.toJson(account.getMetadataStore()));
    write(dir, "protocol-address.json", JsonUtil.toJson(account.getSignalProtocolAddress()));
    write(dir, "contacts.json", JsonUtil.toJson(account.getContactList()));
    write(dir, "messages.json", JsonUtil.toJson(account.getUnencryptedMessages()));
    write(dir, "unique-user-id.json", JsonUtil.toJson(account.getName()));

    // Recorded alongside the fixtures so the compatibility test can assert byte-level equality of
    // the key material rather than merely "it parsed".
    write(dir, "identity-key-pair.b64", com.amnesica.kryptey.inputmethod.signalprotocol.util.Base64
        .encodeBytesWithoutPadding(account.getSignalProtocolStore().getIdentityKeyPair().serialize()));
    write(dir, "registration-id.txt",
        String.valueOf(account.getSignalProtocolStore().getLocalRegistrationId()));
  }

  private static void write(final File dir, final String name, final String content)
      throws IOException {
    try (FileWriter w = new FileWriter(new File(dir, name))) {
      w.write(content);
    }
  }
}
